imports:
    - { resource: tables.yml }

services:
    mot.usermap.functions_usermap:
        class: mot\usermap\includes\functions_usermap
        arguments:
            - '@dbal.conn'
            - '%mot.usermap.tables.usermap_layers%'
        tags:
            - { name: usermap_functions, tag: mot.usermap.functions_usermap }

    mot.usermap.controller:
        class: mot\usermap\controller\main
        arguments:
            - '@auth'
            - '@config'
            - '@config_text'
            - '@controller.helper'
            - '@template'
            - '@dbal.conn'
            - '@user'
            - '@language'
            - '@ext.manager'
            - '@request'
            - '@notification_manager'
            - '@log'
            - '@mot.usermap.functions_usermap'
            - '%core.php_ext%'
            - '%core.root_path%'
            - '%mot.usermap.tables.usermap_users%'
            - '%mot.usermap.tables.usermap_poi%'
            - '%mot.usermap.tables.usermap_layers%'

    mot.usermap.controller.acp_controller:
        class: mot\usermap\controller\mot_usermap_acp
        arguments:
            - '@auth'
            - '@config'
            - '@config_text'
            - '@dbal.conn'
            - '@group_helper'
            - '@language'
            - '@log'
            - '@pagination'
            - '@ext.manager'
            - '@request'
            - '@template'
            - '@user'
            - '@mot.usermap.functions_usermap'
            - '%mot.usermap.tables.usermap_layers%'
            - '%mot.usermap.tables.usermap_poi%'
            - '%mot.usermap.tables.usermap_zipcodes%'

    mot.usermap.mod_poi:
        class: mot\usermap\controller\mod_poi
        arguments:
            - '@auth'
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@dbal.conn'
            - '@user'
            - '@language'
            - '@ext.manager'
            - '@request'
            - '@notification_manager'
            - '@log'
            - '@mot.usermap.functions_usermap'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%mot.usermap.tables.usermap_poi%'
            - '%mot.usermap.tables.usermap_layers%'
        tags:
            - { name: controller.handle }

    mot.usermap.listener:
        class: mot\usermap\event\main_listener
        arguments:
            - '@auth'
            - '@config'
            - '@config_text'
            - '@controller.helper'
            - '@template'
            - '@dbal.conn'
            - '@user'
            - '@log'
            - '@ext.manager'
            - '@language'
            - '%core.php_ext%'
            - '%core.root_path%'
            - '%mot.usermap.tables.usermap_users%'
            - '%mot.usermap.tables.usermap_zipcodes%'
        tags:
            - { name: event.listener }

    mot.usermap.controller.ajax_call:
        class: mot\usermap\controller\ajax_call
        arguments:
            - '@config'
            - '@language'
            - '@request'

    mot.usermap.notification.type.approve_poi:
        class: mot\usermap\notification\approve_poi
        shared: false
        parent: notification.type.base
        calls:
            - [set_user_loader, ['@user_loader']]
            - [set_helper, ['@controller.helper']]
        tags:
            - { name: notification.type }

    mot.usermap.notification.type.notify_poi:
        class: mot\usermap\notification\notify_poi
        shared: false
        parent: notification.type.base
        calls:
            - [set_user_loader, ['@user_loader']]
            - [set_helper, ['@controller.helper']]
        tags:
            - { name: notification.type }
